"""Generate js/colors.js: the average colour of every image under assets/img (+ the book cover).
Used as the placeholder background behind each image while it loads. Run: python scripts/colors.py"""
import glob, os, json
from PIL import Image
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
files = sorted(glob.glob(os.path.join(ROOT, 'assets', 'img', '**', '*.*'), recursive=True)) + [os.path.join(ROOT, 'assets', 'book', 'cover.jpg')]
out = {}
for f in files:
    if not f.lower().endswith(('.jpg', '.jpeg', '.png', '.webp', '.gif')): continue
    try:
        im = Image.open(f); im.seek(0); im = im.convert('RGBA').resize((24, 24), Image.BILINEAR)
        px = [p for p in im.getdata() if p[3] > 40]
        if not px: continue
        r = sum(p[0] for p in px) // len(px); g = sum(p[1] for p in px) // len(px); b = sum(p[2] for p in px) // len(px)
        # keep placeholders in the site's dark register: pull very bright averages down a little
        k = 0.78 if (r + g + b) / 3 > 170 else 1.0
        rel = os.path.relpath(f, ROOT).replace(os.sep, '/')
        out[rel] = '#%02x%02x%02x' % (int(r * k), int(g * k), int(b * k))
    except Exception as e:
        print('skip', f, e)
js = '// Generated by scripts/colors.py — average colour per image, used as the loading placeholder.\nexport const colors = ' + json.dumps(out, indent=0, sort_keys=True) + ';\n'
open(os.path.join(ROOT, 'js', 'colors.js'), 'w', encoding='utf-8').write(js)
print('wrote js/colors.js with', len(out), 'entries')
